// BUSINESS LOGIC ACTIONS
export const REQRES_CLEAR = 'REQRES_CLEAR';
export const REQRES_ADD = 'REQRES_ADD';
export const REQRES_DELETE = 'REQRES_DELETE';
export const REQRES_UPDATE = 'REQRES_UPDATE';

export const GET_HISTORY = 'GET_HISTORY';
export const DELETE_HISTORY = 'DELETE_HISTORY';

export const SET_COMPOSER_WARNING_MESSAGE = "SET_COMPOSER_WARNING_MESSAGE";

export const SET_NEW_REQUEST_FIELDS = "SET_NEW_REQUEST_FIELDS";
export const SET_NEW_REQUEST_HEADERS = "SET_NEW_REQUEST_HEADERS";
export const SET_NEW_REQUEST_BODY = "SET_NEW_REQUEST_BODY";
export const SET_NEW_REQUEST_COOKIES = "SET_NEW_REQUEST_COOKIES";

export const SET_CURRENT_TAB = "SET_CURRENT_TAB";

export const SET_CHECKS_AND_MINIS = "SET_CHECKS_AND_MINIS";

//UI ACTIONS
export const SHOW_WARNING = "SHOW_WARNING";
export const HIDE_WARNING = "HIDE_WARNING";
export const SET_COMPOSER_DISPLAY = "SET_COMPOSER_DISPLAY";
