//BUSINESS LOGIC ACTIONS
export const REQRES_CLEAR = "REQRES_CLEAR";
export const REQRES_ADD = "REQRES_ADD";
export const REQRES_DELETE = "REQRES_DELETE";
export const REQRES_UPDATE = "REQRES_UPDATE";

//UI ACTIONS
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
